name: Run Config Client (Self-Hosted)

on:
  push:        # run on every push for testing
    branches: [ "*" ]
  workflow_dispatch:  # allow manual run too

jobs:
  send-config:
    runs-on: self-hosted   # IMPORTANT: this must match your local runner's label
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Python version
        run: python --version

      - name: Run Config Client
        run: python ConfigClient.py
